= MusicBox

== Menus

    &File
	&New...    ^N # (file new) new musicbox .mb
	&Open...   ^O # (file open)
	&Save...   ^S
	Save &As
	-------------
	&Find...   ^F # on success adds/replaces Search Results/Found in tree
	-------------
	&Configure...
	-------------
	&Quit      ^Q
	-------------
	&1 _most recent musicbox_ # queue-order history
	    :
	&9 _9th least recent musicbox_

    &Group
	&New...	    # group (enter one line of text dialog)
	&Rename...
	-------------
	Move &Up
	Move &Down
	Move to &Group # move to another group or to top-level
	-------------
	&Merge... # merge two groups
	D&uplicate
	-------------
	D&elete...
	&Undelete

    &Track
	&New...	# (file open)
	-------------
	&Play/&Pause      ^P
	&Replay		  ^R
	&Louder           ^+ | ^=
	&Quieter	  ^-
	&Back to Previous ^B
	&Next		  ^N
	-------------
	Move &Up
	Move &Down
	Move to &Group # move to another group or to top-level
	&Copy to Group # add to another group (same track in multi groups is fine)
	-------------
	D&elete...
	&Undelete
	-------------
	&Clear History
	&1 _most recently played_ # history
	    :
	&9 _9th least recent played_

    &Bookmarks
	&1 Add Current Track
	&2 Remove Current Track
	&A _first bookmarked track_
	    :
	&Z _26th bookmarked track_

    &Help
	&Help	    F1
	&About

Could use other Fn keys for common operations?

== Major Dialogs

=== New Group

    &Name  [Group #1   ]
    &Parent Group [   <Top-level> v] # the default; user can add on the fly
    (*) &Add tracks from folder
	[&Folder] ___________________________
    ( ) &Import tracks from playlist
	[&Playlist] _________________________ #.m3u, .pls, .xspf, etc.
    ( ) Create &Empty group
		[&OK] [&Cancel]
    
== UI

    -------------------------------------------------------------
    MusicBox — _musicbox.mb if any_                              X
    -------------------------------------------------------------
    &File &Group &Track &Bookmarks &Help # main menu
    -------------------------------------------------------------
    _main toolbar_
    -------------------------------------------------------------
    _Treeview_                                       | current
    Track #1 ### tracks can be top-level tool        | track
    Group                                            | info
	Group ### groups can be nested to any depth  | frame or
	    Track #1                                 | HtmlView
	    Track #2                                 |
		:                                    |
	    Track #n                                 |
    Track #2                                         :
    Group
	Track #1
	Track #2
	    :
	Track #n
    Search Results ### this only appears if there's a successful search
	Track #1
    -------------------------------------------------------------
    [<<] [@] [>] [>>] [*******   ][3'24"/5'9"] [********** ][95%]
    -------------------------------------------------------------
   
    back replay play/pause next  position  volume
