= MusicBox

== Notes

First create mb/mod.rs mb/*.rs to provide load (both gzipped and
uncompressed `.mb` data), save (of gzipped `.mb` data), and all the
fundamental mb functionality.

Sample files: `~/data/MusicBox-*.mb` (gzipped) and
`~/data/MusicBox-*-txt.mb` (uncompressed). Once loading of both gzipped
and uncompressed `.mb` data works, delete the `~/data/MusicBox-*-txt.mb`
files.

_Then_ add the GUI.

== File Format (.mb)

Note that what's shown here is UTF-8 plain text: the actual `.mb` is
gzipped.

    \fMB\t100
    \fGROUPS
    \vGID\tNAME\tRANK\tPGID
    1\tPop\t0
    2\tThe Eagles\t1
	:
    \fTRACKS
    \vTID\tFILENAME\tSECS\tRANK\tPGID
    1\t/home/mark/music/Eagles/01-Hotel_California.ogg\t2.16\t1\t2
	:
    \fBOOKMARKS
    \vTID
    381
	:
    \fHISTORY
    \vTID
    452
	:
    \fCURRENT
    \vTID # (just one)
    87

All ID's start at 1. Tracks and groups can be top-level. A `pgid` of 0
means top-level.

tracks are ordered by rank within their group (or at the top-level);
groups are ordered by rank within thei group (or at the top-level).

The `secs` is `-1` if unknown. But if all are known then we can report
the total length of the group, and if all groups have totals, then the
group's total, and if all the groups have totals, then the entire music
box's total.

No group may be called "Search Results" "Search Results\t" since this
name is used by MusicBox itself.

The API and the GUI must dissallow group or track names to include any
of `<>:"/\\|?*\t\f`.

== Menus

    &File
	&New...    ^N # (file new) new musicbox .mb
	&Open...   ^O # (file open)
	&Save...   ^S
	Save &As
	-------------
	&Find...   ^F # on success adds/replaces Search Results/Found in tree
	-------------
	&Configure...
	-------------
	&Quit      ^Q
	-------------
	&1 _most recent musicbox_ # queue-order
	    :
	&9 _9th least recent musicbox_

    &Group
	&New...	    # group (enter one line of text dialog)
	&Rename...
	-------------
	Move &Up    # rank
	Move &Down
	Move to &Group # move to another group or to top-level
	-------------
	D&elete...

    &Track
	&New...	# (file open)
	-------------
	&Play/&Pause      ^P
	&Replay		  ^R
	&Louder           ^+ | ^=
	&Quieter	  ^-
	&Back to Previous ^B
	&Next		  ^N
	-------------
	Move &Up    # rank
	Move &Down
	Move to &Group # move to another group or to top-level
	&Copy to Group # add to another group (same track in multi groups is fine)
	-------------
	D&elete...
	-------------
	&Clear History
	&1 _most recently played_ # history
	    :
	&9 _9th least recent played_

    &Bookmarks
	&1 Add Current Track
	&2 Remove Current Track
	&A _first bookmarked track_
	    :
	&Z _26th bookmarked track_

    &Help
	&Help	    F1
	&About

Could use other Fn keys for common operations?

== Major Dialogs

=== New Group

    &Name  [Group #1   ]
    &Parent Group [   <Top-level> v] # the default; user can add on the fly
    (*) &Add tracks from folder
	[&Folder] ___________________________
    ( ) &Import tracks from playlist
	[&Playlist] _________________________ #.m3u, .pls, .xspf, etc.
    ( ) Create &Empty group
		[&OK] [&Cancel]
    
== UI

    -------------------------------------------------------------
    MusicBox — _musicbox.mb if any_                              X
    -------------------------------------------------------------
    &File &Group &Track &Bookmarks &Help # main menu
    -------------------------------------------------------------
    _main toolbar_
    -------------------------------------------------------------
    _Treeview_
    Track #1 ### tracks can be top-level tool
    Group
	Group ### groups can be nested to any depth
	    Track #1
	    Track #2
		:
	    Track #n
    Track #2
    Group
	Track #1
	Track #2
	    :
	Track #n
    Search Results ### this only appears if there's a successful search
	Track #1
    -------------------------------------------------------------
    status line: currently playing track's artist
    -------------------------------------------------------------
    [<<] [@] [>] [>>] [*******   ][3'24"/5'9"] [********** ][95%]
    -------------------------------------------------------------
   
    back replay play/pause next  position  volume
