= MusicBox

== Notes

First create mb/mod.rs mb/*.rs to provide load (both gzipped and
uncompressed `.mb` data), save (of gzipped `.mb` data), and all the
fundamental mb functionality.

Sample files: `~/data/Playlist-*.mb` (gzipped) and
`~/data/Playlist-*-txt.mb` (uncompressed). Once loading of both gzipped
and uncompressed `.mb` data works, delete the `~/data/Playlist-*-txt.mb`
files.

_Then_ add the GUI.

== File Format (.ple)

Note that what's shown here is UTF-8 plain text: the actual `.mb` is
gzipped.

    *MB>100
    *G
    group1
	:
    groupN # any number of groups (listed in rank order)
    *C
    group>playlist>track>pos
    *H
    group>playlist>track1
	:
    group>playlist>track9 # max of 9 (listed in queue order)
    *P>group>playlist1
    track1>secs
	:
    trackN>secs # any number of tracks
    *P>group>playlist2
    track1>secs
	:
    trackN>secs # any number of tracks listed in rank order
    # any number of playlists listed in rank order

For current (`*C`) pos and for playlist (`*P`) length use one decimal
place.

When an `.mb` file is read, the first group is given the rank 1, the
second 2, etc. If a group is moved up through the GUI, its rank is
swapped with the group before (or left unchanged if it is first).
Similarly, if a group is moved down, its rank is swapped with the group
after (or left unchanged if it is last). Any new group gets a rank of
groups max rank + 1. This approach is also applied to playlists and
tracks.

When a `.mb` file is written, groups, playlists, and tracks are written
out in rank order, with new ranks being given (starting at 1) so that
there are no gaps (e.g., if any were deleted during user interaction).

The `secs` is `-1` if unknown. But if all are known then we can report
the total length of the playlist, and if all playlists in the group have
totals, then the group's total, and if all the groups have totals, then
the entire music box's total.

Every playlist is in a group (default is "Ungrouped"); groups do _not_
nest.

No playlist may be called "Ungrouped" or "Found"; no group may be called
"Search Results" since these names are used by MusicBox itself.

Clearly the API and the GUI must dissallow group, playlist, or track
names to include any of `<>:"/\\|?*`.

== Menus

    &File
	&New...    ^N # (file new) new musicbox .mb
	&Open...   ^O # (file open)
	&Save...   ^S
	Save &As
	-------------
	&Find...   ^F # on success adds/replaces Search Results/Found in tree
	-------------
	&Configure...
	-------------
	&Quit      ^Q
	-------------
	&1 _most recent musicbox_ # queue-order
	    :
	&9 _9th least recent musicbox_

    &Group
	&New...	    # group (enter one line of text dialog)
	&Rename...
	-------------
	Move &Up    # rank
	Move &Down
	-------------
	D&elete...

    &Playlist
	&New...	    # playlist
	&Rename...
	E&xport... # to .m3u, .pls, .xspf, etc.
	-------------
	Move &Up    # rank
	Move &Down
	Move to &Group # change group
	-------------
	D&elete...

    &Track
	&New...	# (file open)
	-------------
	&Play/&Pause      ^P
	&Replay		  ^R
	&Louder           ^+ | ^=
	&Quieter	  ^-
	&Back to Previous ^B
	&Next		  ^N
	-------------
	Move &Up    # rank
	Move &Down
	Move to &Playlist # change playlist
	&Copy to Playlist # add to another playlist (same track in multi playlists is fine)
	-------------
	D&elete...
	-------------
	&Clear History
	&1 _most recently played_ # history
	    :
	&9 _9th least recent played_

    &Bookmarks
	&1 Add Current Track
	&2 Remove Current Track
	&A _first bookmarked track_
	    :
	&Z _26th bookmarked track_

    &Help
	&Help	    F1
	&About

Could use other Fn keys for common operations?

== Major Dialogs

=== New Playlist

    &Name  [Playlist #1   ]
    &Group [   Ungrouped v] # the default; user can add on the fly
    (*) &Add tracks from folder
	[&Folder] ___________________________
    ( ) &Import tracks from playlist
	[&Playlist] _________________________ #.m3u, .pls, .xspf, etc.
    ( ) Create &Empty playlist
		[&OK] [&Cancel]
    
== UI

    -------------------------------------------------------------
    MusicBox — _musicbox.mb if any_                              X
    -------------------------------------------------------------
    &File &Group &Playlist &Track &Bookmarks &Help # main menu
    -------------------------------------------------------------
    _main toolbar_
    -------------------------------------------------------------
    _Treeview_
    Group
	Playlist
	    Track #1
	    Track #2
		:
	    Track #n
    Group
	Playlist
	    Track #1
	    Track #2
		:
	    Track #n
    Search Results ### this only appears if there's a successful search
	Found
	    Track #1
    -------------------------------------------------------------
    status line: currently playing track's artist
    -------------------------------------------------------------
    [<<] [@] [>] [>>] [*******   ][3'24"/5'9"] [********** ][95%]
    -------------------------------------------------------------
   
    back replay play/pause next  position  volume
