= TLM

“Track List Manager” — an application to manage playlists and play tracks.

== Menus

    &File
	&New...    ^N # (file new) new database .tlm
	&Open...   ^O # (file open)
	Open &Recent → &1 ... &9
	&Save...   ^S
	Save &As...
	-------------
	&Configure...
	-------------
	&Quit      ^Q

    &List
	&New...	    # list (enter one line of text dialog)
	&Rename...
	-------------
	Move &Up
	Move &Down
	Move &To... # move to another list or to top-level
	-------------
	&Merge... # merge two lists
	&Copy
	-------------
	E&xport... # to .m3u, .pls, .xspf, etc.
	&Import... # from .m3u, .pls, .xspf, etc. (like List→New)
	-------------
	D&elete...
	Unde&lete

    &Track
	&New...		  # (file open)
	-------------
	Play Pre&vious	  F4
	&Play/&Pause      F5
	&Replay		  F6
	Play Nex&t	  F7
	&Increase Volume  Shift+F8
	Decre&ase Volume  F8
	-------------
	Move &Up
	Move &Down
	&Move to List # move to another list or to top-level
	&Copy to List # add to another list (same track in multi list is fine)
	-------------
	&Find...   ^F # on success adds/replaces Search Results/Found in tree
	-------------
	D&elete...
	Unde&lete

    &History
	Clear History
	&1 _most recently played_ # history
	    :
	&9 _9th least recent played_
	&A ... &Z

    &Bookmarks
	Add Current Track
	Remove Current Track
	&1 _first bookmarked track_
	    :
	&9 _9th bookmarked track_
	&A ... &Z

    &Help
	&Help	    F1
	&About

Could use other Fn keys for common operations?

== Major Dialogs

=== New List

    &Name  [List #1   ] # based of folder name but editable
    &Parent List [   <Top-level> v] # the default; user can add on the fly
    (*) &Add tracks from folder
	[&Folder] ___________________________
    ( ) &Import tracks from playlist
	[&Playlist] _________________________ #.m3u, .pls, .xspf, etc.
    ( ) Create &Empty List
		[&OK] [&Cancel]
    
== UI

    -------------------------------------------------------------
    TLM — _playlists.tlm if any_                              |X|
    -------------------------------------------------------------
    &File &List &Track &Bookmarks &Help # main menu
    -------------------------------------------------------------
    _main toolbar_
    -------------------------------------------------------------
    _Treeview_                                       | current
    Track #1 ### tracks can be top-level tool        | track
    List                                             | info
	List ### lists can be nested to any depth    | HtmlView 
	    Track #1                                 |
	    Track #2                                 |
		:                                    |
	    Track #n                                 |
    Track #2                                         :
    List
	Track #1
	Track #2
	    :
	Track #n
    Search Results ### this list only appears if there's a successful search
	Track #1
    -------------------------------------------------------------
    [<<] [@] [>] [>>] [*******   ][3'24"/5'9"] [********** ][95%]
    -------------------------------------------------------------
   
    back replay play/pause next  position  volume
